=== Sontran-1928/COMP3760-Assignment-3/booking.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

	<xsd:element name="booking">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="activities" type="activitiesType"/>
				<xsd:element name="detail" type="credentialDetail"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>	
	
	<xsd:complexType name="credentialDetail">
		<xsd:sequence>
			<xsd:element name="firstName" type="xsd:string"/>
			<xsd:element name="creditCardNumber" type="xsd:string"/>
			<xsd:element name="expireDate" type="xsd:gYearMonth"/>
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="activitiesType">
		<xsd:sequence>
			<xsd:element name="activity" type="activityType" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="activityType">
		<xsd:choice maxOccurs="unbounded">
			<xsd:element name="hotel" type="hotelOrderType"/>
			<xsd:element name="movie" type="activityOrderType"/>
			<xsd:element name="activity" type="activityOrderType"/>
		</xsd:choice>
	</xsd:complexType>
	
	<xsd:complexType name="hotelOrderType">
		<xsd:sequence>
			<xsd:element name="hotelName" type="xsd:string"/>
			<xsd:element name="attendees" type="xsd:integer"/>
			<xsd:element name="startTime" type="xsd:dateTime"/>
			<xsd:element name="endTime" type="xsd:dateTime"/>
			<xsd:element name="price" type="priceType"/>
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="activityOrderType">
		<xsd:sequence>
			<xsd:element name="activityName" type="xsd:string"/>
			<xsd:element name="attendees" type="xsd:integer"/>
			<xsd:element name="startTime" type="xsd:dateTime"/>
			<xsd:element name="price" type="priceType"/>
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="priceType">
		<xsd:simpleContent>
			<xsd:extension base="xsd:decimal">
				<xsd:attribute name="currency" type="xsd:token"/>
			</xsd:extension>
		</xsd:simpleContent>
	</xsd:complexType>
</xsd:schema>

=== Sontran-1928/COMP3760-Assignment-3/booking.xml
<booking xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="booking.xsd">

	<activities>
		<activity>
			<movie>
				<activityName>Shrek</activityName>
				<attendees>2</attendees>
				<startTime>2024-07-02T18:00:00</startTime>
				<price>19.99</price>
			</movie>
		</activity>
	</activities>
	
	<detail>
		<firstName>Son</firstName>
		<creditCardNumber>123456789</creditCardNumber>
		<expireDate>2024-10</expireDate>
	</detail>
</booking>
