=== Sontran-1928/COMP3760-Assignment-3/recommendation.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

	<xsd:element name="recommendation">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="lookUp" type="lookUpDetail"/>
				<xsd:element name="recommend" type="recommendPlaces"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:complexType name="lookUpDetail">
		<xsd:sequence minOccurs="1" maxOccurs="1">
			<xsd:element name="destination" type="xsd:string"/>
			<xsd:element name="attendees" type="xsd:integer"/>
			<xsd:element name="travelDate" type="xsd:date"/>
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="recommendPlaces">
		<xsd:choice maxOccurs="unbounded">
			<xsd:element name="travel" type="travelRecommend"/>
			<xsd:element name="hotel" type="hotelRecommend"/>
			<xsd:element name="activities" type="activitiesRecommend"/>
		</xsd:choice>
	</xsd:complexType>

	<xsd:complexType name="travelRecommend">
		<xsd:choice maxOccurs="unbounded">
			<xsd:element name="flight" type="travelDetail"/>
			<xsd:element name="ship" type="travelDetail"/>
			<xsd:element name="road" type="travelDetail"/>
		</xsd:choice>
	</xsd:complexType>

	<xsd:complexType name="travelDetail">
		<xsd:sequence>
			<xsd:element name="travelCompany" type="xsd:string"/>
			<xsd:element name="travelFrom" type="xsd:string"/>
			<xsd:element name="travelTo" type="xsd:string"/>
			<xsd:element name="travelDuration" type="xsd:duration"/>
			<xsd:element name="travelStops" type="xsd:integer" minOccurs="0" maxOccurs="1"/>
			<xsd:element name="price" type="priceType"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="hotelRecommend">
		<xsd:sequence>
			<xsd:element name="hotelName" type="xsd:string"/>
			<xsd:element name="hotelAddress" type="xsd:string"/>
			
			<xsd:element name="hotelStarRating">
				<xsd:simpleType>
					<xsd:restriction base="xsd:decimal">
						<xsd:fractionDigits value="1"/>
						<xsd:minInclusive value="0"/>
						<xsd:maxInclusive value="5"/>
						<xsd:pattern value="[0-5].[05]"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			
			<xsd:element name="pricePerNight" type="priceType"/>
			
			<xsd:element name="hotelPhoneNumber">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="10"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="activitiesRecommend">
		<xsd:sequence>
			<xsd:element name="activity" type="activityRecommend" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="activityRecommend">
		<xsd:sequence>
			<xsd:element name="activityType" type="xsd:string"/>
			<xsd:element name="activityName" type="xsd:string"/>
			<xsd:element name="activityCompany" type="xsd:string" minOccurs="0" maxOccurs="1"/>
			<xsd:element name="activityLocation" type="xsd:string"/>
			<xsd:element name="activityStartTime" type="xsd:dateTime"/>
			<xsd:element name="activityDuration" type="xsd:duration"/>
			<xsd:element name="price" type="priceType"/>
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="priceType">
		<xsd:simpleContent>
			<xsd:extension base="xsd:decimal">
				<xsd:attribute name="currency" type="xsd:token"/>
			</xsd:extension>
		</xsd:simpleContent>
	</xsd:complexType>
</xsd:schema>

=== Sontran-1928/COMP3760-Assignment-3/recommendation.xml
<recommendation xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="recommendation.xsd">
	   
	<lookUp>
		<destination>Sydney</destination>
		<attendees>2</attendees>
		<travelDate>2024-10-18</travelDate>
	</lookUp>
	
	<recommend>
		<travel>
			<flight>
				<travelCompany>Quantas</travelCompany>
				<travelFrom>Perth</travelFrom>
				<travelTo>Sydney</travelTo>
				<travelDuration>PT4H10M</travelDuration>
				<price currency="AUS">830</price>
			</flight>
			<ship>
				<travelCompany>Cunard</travelCompany>
				<travelFrom>Perth</travelFrom>
				<travelTo>Sydney</travelTo>
				<travelDuration>P12D</travelDuration>
				<travelStops>12</travelStops>
				<price currency="AUS">4400</price>
			</ship>
		</travel>
		
		<hotel>
			<hotelName>Sydney Boutique Hotel</hotelName>
			<hotelAddress>114 Darlinghurst Rd, Darlinghurst NSW 2010</hotelAddress>
			<hotelStarRating>4.0</hotelStarRating>
			<pricePerNight currency="AUS">160.00</pricePerNight>
			<hotelPhoneNumber>0280185636</hotelPhoneNumber>
		</hotel>
		
		<activities>
			<activity>
				<activityType>Movie</activityType>
				<activityName>Shrek</activityName>
				<activityCompany>IMAX</activityCompany>
				<activityLocation>1/35 Wheat Rd, Sydney NSW 2000</activityLocation>
				<activityStartTime>2024-10-19T18:00:00</activityStartTime>
				<activityDuration>PT1H30M</activityDuration>
				<price currency="AUS">9.99</price>
			</activity>
			
			<activity>
				<activityType>Museum</activityType>
				<activityName>Museum of Sydney</activityName>
				<activityLocation>Cnr Bridge St, Phillip St, Sydney NSW 2000</activityLocation>
				<activityStartTime>2024-10-20T13:00:00</activityStartTime>
				<activityDuration>PT2H</activityDuration>
				<price currency="AUS">20</price>
			</activity>
		</activities>
	</recommend>
	
</recommendation>
